### PR TITLE
feat: Adding maxTime param to retrieve from DB only recent points

### PR DESCRIPTION
**Pull request by danielherrerohernando**
## What’s the focus of this PR
This PR updates DB query in order to fetch only "recent" points as suggested by @jadorado .
The time param is set via config and a default value has been set corresponding to one month.

## How to review this PR
Just check mongo file with the updated query.

Before submitting this PR, I made sure:

- [x] The code builds clean without any errors or warnings
- [x] I'm using our guidelines

### CODE REVIEW

**Review by feliun — CHANGES_REQUESTED** [review]
@danielherrerohernando my thoughts:

I like the approach - in the long term this "maxTimeGap" may come from a query param injected by a UI filter (potentially).

My only comment is that the query `find` query does not need the $and modifier as you could do

`.find({ team, timestamp: { $gt : calculateFromWhen(config.maxTimeGap) } } })`

**Comment by danielherrerohernando** [comment]
> @danielherrerohernando my thoughts:
> 
> I like the approach - in the long term this "maxTimeGap" may come from a query param injected by a UI filter (potentially).
Sure, this maxTimeGap set in the config could remain being the fallback if no valid param is provided in the GET request.

> My only comment is that the query `find` query does not need the $and modifier as you could do
> 
> `.find({ team, timestamp: { $gt : calculateFromWhen(config.maxTimeGap) } } })`

100% agree. Updated accordingly @feliun

**Review by feliun — CHANGES_REQUESTED** [review]
I don't think that's going to work as you've placed the 2 components of the query as 2 parameters.

We'd need something like:

`find({ ...teamQuery, ...timeQuery })` 

to make it work properly (otherwise the second parameter will be considered as the projection, based on the docs): https://docs.mongodb.com/manual/reference/method/db.collection.find/

**Comment by danielherrerohernando** [comment]
You'r right, my bad, already updated.

**Review by feliun — APPROVED** [review]
Thanks @danielherrerohernando - I will merge and deploy on Monday so I can test locally with more time

**Pull request merged**
